spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simplejpa
    username: simplejpa
    password: simplejpa
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000

logging:
  pattern:
  level:
    org.hibernate.orm.jdbc.bind: trace